/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.programacao.exercicios;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class Exercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio2
     */
    public Exercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPesoTerra = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblSelecionePlaneta = new javax.swing.JLabel();
        rbMercurio = new javax.swing.JRadioButton();
        rbVenus = new javax.swing.JRadioButton();
        rbMarte = new javax.swing.JRadioButton();
        rbJupiter = new javax.swing.JRadioButton();
        rbSaturno = new javax.swing.JRadioButton();
        rbUrano = new javax.swing.JRadioButton();
        btnPeso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPesoTerra.setText("Peso na Terra (Kg):");

        lblSelecionePlaneta.setText("Selecione o Planeta");

        rbMercurio.setText("Mercurio");
        rbMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMercurioActionPerformed(evt);
            }
        });

        rbVenus.setText("Vênus");
        rbVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVenusActionPerformed(evt);
            }
        });

        rbMarte.setText("Marte");
        rbMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMarteActionPerformed(evt);
            }
        });

        rbJupiter.setText("Júpiter");
        rbJupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJupiterActionPerformed(evt);
            }
        });

        rbSaturno.setText("Saturno");
        rbSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSaturnoActionPerformed(evt);
            }
        });

        rbUrano.setText("Urano");
        rbUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUranoActionPerformed(evt);
            }
        });

        btnPeso.setText("Calcular Peso");
        btnPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblPesoTerra))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelecionePlaneta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(btnPeso))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMercurio)
                            .addComponent(rbVenus)
                            .addComponent(rbMarte))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbUrano)
                            .addComponent(rbSaturno)
                            .addComponent(rbJupiter))))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblPesoTerra)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeso))
                .addGap(30, 30, 30)
                .addComponent(lblSelecionePlaneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMercurio)
                    .addComponent(rbJupiter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVenus)
                    .addComponent(rbSaturno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMarte)
                    .addComponent(rbUrano))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMercurioActionPerformed
rbVenus.setSelected(false); 

rbMarte.setSelected(false);
rbJupiter.setSelected(false);
rbSaturno.setSelected(false);
rbUrano.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_rbMercurioActionPerformed

    private void rbVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVenusActionPerformed
  rbMercurio.setSelected(false); 

rbMarte.setSelected(false);
rbJupiter.setSelected(false);
rbSaturno.setSelected(false);
rbUrano.setSelected(false);      // TODO add your handling code here:
    }//GEN-LAST:event_rbVenusActionPerformed

    private void rbMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMarteActionPerformed
  rbMercurio.setSelected(false); 

rbVenus.setSelected(false);
rbJupiter.setSelected(false);
rbSaturno.setSelected(false);
rbUrano.setSelected(false);           // TODO add your handling code here:
    }//GEN-LAST:event_rbMarteActionPerformed

    private void rbJupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJupiterActionPerformed
rbMercurio.setSelected(false); 

rbVenus.setSelected(false);
rbMarte.setSelected(false);
rbSaturno.setSelected(false);
rbUrano.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_rbJupiterActionPerformed

    private void rbSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSaturnoActionPerformed
rbMercurio.setSelected(false); 

rbVenus.setSelected(false);
rbMarte.setSelected(false);
rbJupiter.setSelected(false);
rbUrano.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbSaturnoActionPerformed

    private void rbUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUranoActionPerformed
rbMercurio.setSelected(false); 

rbVenus.setSelected(false);
rbMarte.setSelected(false);
rbJupiter.setSelected(false);
rbSaturno.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbUranoActionPerformed

    private void btnPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoActionPerformed
double peso = Double.parseDouble(txtPeso.getText());
double planeta;
if (rbMercurio.isSelected()){
    planeta = peso * 0.37;
    JOptionPane.showMessageDialog(null, "O seu peso em Mercurio é " + planeta);
    
}

else if (rbVenus.isSelected ()){
    planeta = peso * 0.88;
    JOptionPane.showMessageDialog(null, "O seu peso em Vênus é " + planeta);
    
}

else if (rbMarte.isSelected()){
    planeta = peso * 0.38;
    JOptionPane.showMessageDialog(null, "O seu peso em Marte é " + planeta);
    
}
else if (rbJupiter.isSelected()){
    planeta = peso * 2.64;
    JOptionPane.showMessageDialog(null, "O seu peso em Jupiter é " + planeta);
    
}


else if (rbSaturno.isSelected()){
    planeta = peso * 1.15;
    JOptionPane.showMessageDialog(null, "O seu peso em Saturno é " + planeta);
    
}

else {
     planeta = peso * 1.17;
    JOptionPane.showMessageDialog(null, "O seu peso em Urano é " + planeta);
    
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeso;
    private javax.swing.JLabel lblPesoTerra;
    private javax.swing.JLabel lblSelecionePlaneta;
    private javax.swing.JRadioButton rbJupiter;
    private javax.swing.JRadioButton rbMarte;
    private javax.swing.JRadioButton rbMercurio;
    private javax.swing.JRadioButton rbSaturno;
    private javax.swing.JRadioButton rbUrano;
    private javax.swing.JRadioButton rbVenus;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
